/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Badge = IDL.Variant({
  'dsaMasterCat' : IDL.Null,
  'legendaryScholar' : IDL.Null,
  'persistentRabbit' : IDL.Null,
});
export const Time = IDL.Int;
export const DailyRecord = IDL.Record({
  'questionsSolved' : IDL.Nat,
  'date' : Time,
  'penaltyApplied' : IDL.Nat,
});
export const Principal = IDL.Principal;
export const UserProfile = IDL.Record({
  'totalQuestionsSolved' : IDL.Nat,
  'name' : IDL.Text,
  'totalFine' : IDL.Nat,
  'badge' : IDL.Opt(Badge),
  'currentStreak' : IDL.Nat,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
});
export const ChatUser = IDL.Record({
  'principal' : Principal,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfileIfMissing' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllLifetimeStats' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'highestDailyQuestions' : IDL.Nat,
            'totalQuestionsSolved' : IDL.Nat,
            'name' : IDL.Text,
            'totalFine' : IDL.Nat,
            'badge' : IDL.Opt(Badge),
            'currentStreak' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getAllUserStats' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'highestDailyQuestions' : IDL.Nat,
            'totalQuestionsSolved' : IDL.Nat,
            'name' : IDL.Text,
            'totalFine' : IDL.Nat,
            'dailyRecords' : IDL.Vec(DailyRecord),
            'badge' : IDL.Opt(Badge),
            'currentStreak' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([Principal], [IDL.Vec(Message)], ['query']),
  'getChatUsers' : IDL.Func([], [IDL.Vec(ChatUser)], ['query']),
  'getDailyHistory' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'highestDailyQuestions' : IDL.Nat,
          'totalQuestionsSolved' : IDL.Nat,
          'todayQuestions' : IDL.Nat,
          'totalFine' : IDL.Nat,
          'badge' : IDL.Opt(Badge),
          'currentStreak' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTodayQuestions' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserDailyHistory' : IDL.Func(
      [Principal],
      [IDL.Vec(DailyRecord)],
      ['query'],
    ),
  'getUserLifetimeStats' : IDL.Func(
      [Principal],
      [IDL.Record({ 'totalQuestionsSolved' : IDL.Nat, 'totalFine' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserStats' : IDL.Func(
      [Principal],
      [
        IDL.Opt(
          IDL.Record({
            'highestDailyQuestions' : IDL.Nat,
            'todayQuestions' : IDL.Nat,
            'profile' : UserProfile,
            'recordCount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDailyChallengeCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAllUserData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Principal, IDL.Text], [], []),
  'setTodayQuestionsForUser' : IDL.Func([Principal, IDL.Nat], [], []),
  'triggerDailyReset' : IDL.Func([], [], []),
  'updateTodayQuestions' : IDL.Func([IDL.Nat], [], []),
  'updateYesterdayData' : IDL.Func([], [IDL.Text], []),
  'verifyAccountExists' : IDL.Func(
      [],
      [IDL.Record({ 'accountCreated' : IDL.Bool, 'exists' : IDL.Bool })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Badge = IDL.Variant({
    'dsaMasterCat' : IDL.Null,
    'legendaryScholar' : IDL.Null,
    'persistentRabbit' : IDL.Null,
  });
  const Time = IDL.Int;
  const DailyRecord = IDL.Record({
    'questionsSolved' : IDL.Nat,
    'date' : Time,
    'penaltyApplied' : IDL.Nat,
  });
  const Principal = IDL.Principal;
  const UserProfile = IDL.Record({
    'totalQuestionsSolved' : IDL.Nat,
    'name' : IDL.Text,
    'totalFine' : IDL.Nat,
    'badge' : IDL.Opt(Badge),
    'currentStreak' : IDL.Nat,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : Principal,
    'timestamp' : Time,
    'receiver' : Principal,
  });
  const ChatUser = IDL.Record({ 'principal' : Principal, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfileIfMissing' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllLifetimeStats' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'highestDailyQuestions' : IDL.Nat,
              'totalQuestionsSolved' : IDL.Nat,
              'name' : IDL.Text,
              'totalFine' : IDL.Nat,
              'badge' : IDL.Opt(Badge),
              'currentStreak' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getAllUserStats' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'highestDailyQuestions' : IDL.Nat,
              'totalQuestionsSolved' : IDL.Nat,
              'name' : IDL.Text,
              'totalFine' : IDL.Nat,
              'dailyRecords' : IDL.Vec(DailyRecord),
              'badge' : IDL.Opt(Badge),
              'currentStreak' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([Principal], [IDL.Vec(Message)], ['query']),
    'getChatUsers' : IDL.Func([], [IDL.Vec(ChatUser)], ['query']),
    'getDailyHistory' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'highestDailyQuestions' : IDL.Nat,
            'totalQuestionsSolved' : IDL.Nat,
            'todayQuestions' : IDL.Nat,
            'totalFine' : IDL.Nat,
            'badge' : IDL.Opt(Badge),
            'currentStreak' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTodayQuestions' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserDailyHistory' : IDL.Func(
        [Principal],
        [IDL.Vec(DailyRecord)],
        ['query'],
      ),
    'getUserLifetimeStats' : IDL.Func(
        [Principal],
        [
          IDL.Record({
            'totalQuestionsSolved' : IDL.Nat,
            'totalFine' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserStats' : IDL.Func(
        [Principal],
        [
          IDL.Opt(
            IDL.Record({
              'highestDailyQuestions' : IDL.Nat,
              'todayQuestions' : IDL.Nat,
              'profile' : UserProfile,
              'recordCount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDailyChallengeCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAllUserData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Principal, IDL.Text], [], []),
    'setTodayQuestionsForUser' : IDL.Func([Principal, IDL.Nat], [], []),
    'triggerDailyReset' : IDL.Func([], [], []),
    'updateTodayQuestions' : IDL.Func([IDL.Nat], [], []),
    'updateYesterdayData' : IDL.Func([], [IDL.Text], []),
    'verifyAccountExists' : IDL.Func(
        [],
        [IDL.Record({ 'accountCreated' : IDL.Bool, 'exists' : IDL.Bool })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };