/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = { 'dsaMasterCat' : null } |
  { 'legendaryScholar' : null } |
  { 'persistentRabbit' : null };
export interface ChatUser { 'principal' : Principal, 'name' : string }
export interface DailyRecord {
  'questionsSolved' : bigint,
  'date' : Time,
  'penaltyApplied' : bigint,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type Principal = Principal;
export type Time = bigint;
export interface UserProfile {
  'totalQuestionsSolved' : bigint,
  'name' : string,
  'totalFine' : bigint,
  'badge' : [] | [Badge],
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfileIfMissing' : ActorMethod<[string], string>,
  'getAllLifetimeStats' : ActorMethod<
    [],
    Array<
      {
        'highestDailyQuestions' : bigint,
        'totalQuestionsSolved' : bigint,
        'name' : string,
        'totalFine' : bigint,
        'badge' : [] | [Badge],
        'currentStreak' : bigint,
      }
    >
  >,
  'getAllUserStats' : ActorMethod<
    [],
    Array<
      {
        'highestDailyQuestions' : bigint,
        'totalQuestionsSolved' : bigint,
        'name' : string,
        'totalFine' : bigint,
        'dailyRecords' : Array<DailyRecord>,
        'badge' : [] | [Badge],
        'currentStreak' : bigint,
      }
    >
  >,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChat' : ActorMethod<[Principal], Array<Message>>,
  'getChatUsers' : ActorMethod<[], Array<ChatUser>>,
  'getDailyHistory' : ActorMethod<[], Array<DailyRecord>>,
  'getStats' : ActorMethod<
    [],
    {
      'highestDailyQuestions' : bigint,
      'totalQuestionsSolved' : bigint,
      'todayQuestions' : bigint,
      'totalFine' : bigint,
      'badge' : [] | [Badge],
      'currentStreak' : bigint,
    }
  >,
  'getTodayQuestions' : ActorMethod<[], bigint>,
  'getUserDailyHistory' : ActorMethod<[Principal], Array<DailyRecord>>,
  'getUserLifetimeStats' : ActorMethod<
    [Principal],
    { 'totalQuestionsSolved' : bigint, 'totalFine' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<
    [Principal],
    [] | [
      {
        'highestDailyQuestions' : bigint,
        'todayQuestions' : bigint,
        'profile' : UserProfile,
        'recordCount' : bigint,
      }
    ]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDailyChallengeCompleted' : ActorMethod<[], boolean>,
  'resetAllUserData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setTodayQuestionsForUser' : ActorMethod<[Principal, bigint], undefined>,
  'triggerDailyReset' : ActorMethod<[], undefined>,
  'updateTodayQuestions' : ActorMethod<[bigint], undefined>,
  'updateYesterdayData' : ActorMethod<[], string>,
  'verifyAccountExists' : ActorMethod<
    [],
    { 'accountCreated' : boolean, 'exists' : boolean }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];