/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type Principal = Principal;
export interface Message {
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface DailyRecord {
    date: Time;
    penaltyApplied: bigint;
    problemsSolved: bigint;
}
export interface ChatUser {
    principal: Principal;
    name: string;
}
export interface UserProfile {
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
}
export enum Badge {
    dsaMasterCat = "dsaMasterCat",
    legendaryScholar = "legendaryScholar",
    persistentRabbit = "persistentRabbit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createUserProfileIfMissing(name: string): Promise<string>;
    getAllLifetimeStats(): Promise<Array<{
        name: string;
        totalFine: bigint;
        totalProblemsSolved: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }>>;
    getAllUserStats(): Promise<Array<{
        name: string;
        totalFine: bigint;
        dailyRecords: Array<DailyRecord>;
        totalProblemsSolved: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }>>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getChat(receiver: Principal): Promise<Array<Message>>;
    getChatUsers(): Promise<Array<ChatUser>>;
    getDailyHistory(): Promise<Array<DailyRecord>>;
    getStats(): Promise<{
        totalFine: bigint;
        totalProblemsSolved: bigint;
        todayProblems: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }>;
    getTodayProblems(): Promise<bigint>;
    getUserDailyHistory(user: Principal): Promise<Array<DailyRecord>>;
    getUserLifetimeStats(user: Principal): Promise<{
        totalFine: bigint;
        totalProblemsSolved: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStats(user: Principal): Promise<{
        todayProblems: bigint;
        profile: UserProfile;
        recordCount: bigint;
    } | null>;
    isCallerAdmin(): Promise<boolean>;
    isDailyChallengeCompleted(): Promise<boolean>;
    resetAllUserData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(receiver: Principal, content: string): Promise<void>;
    setTodayProblemsForUser(user: Principal, count: bigint): Promise<void>;
    triggerDailyReset(): Promise<void>;
    updateTodayProblems(count: bigint): Promise<void>;
    updateYesterdayData(): Promise<string>;
    verifyAccountExists(): Promise<{
        accountCreated: boolean;
        exists: boolean;
    }>;
}
import type { Badge as _Badge, DailyRecord as _DailyRecord, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUserProfileIfMissing(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfileIfMissing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfileIfMissing(arg0);
            return result;
        }
    }
    async getAllLifetimeStats(): Promise<Array<{
        name: string;
        totalFine: bigint;
        totalProblemsSolved: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLifetimeStats();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLifetimeStats();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserStats(): Promise<Array<{
        name: string;
        totalFine: bigint;
        dailyRecords: Array<DailyRecord>;
        totalProblemsSolved: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserStats();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserStats();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChat(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChat(arg0);
            return result;
        }
    }
    async getChatUsers(): Promise<Array<ChatUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatUsers();
            return result;
        }
    }
    async getDailyHistory(): Promise<Array<DailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyHistory();
            return result;
        }
    }
    async getStats(): Promise<{
        totalFine: bigint;
        totalProblemsSolved: bigint;
        todayProblems: bigint;
        badge?: Badge;
        currentStreak: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayProblems(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayProblems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayProblems();
            return result;
        }
    }
    async getUserDailyHistory(arg0: Principal): Promise<Array<DailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDailyHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDailyHistory(arg0);
            return result;
        }
    }
    async getUserLifetimeStats(arg0: Principal): Promise<{
        totalFine: bigint;
        totalProblemsSolved: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLifetimeStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLifetimeStats(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(arg0: Principal): Promise<{
        todayProblems: bigint;
        profile: UserProfile;
        recordCount: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDailyChallengeCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDailyChallengeCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDailyChallengeCompleted();
            return result;
        }
    }
    async resetAllUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllUserData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setTodayProblemsForUser(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTodayProblemsForUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTodayProblemsForUser(arg0, arg1);
            return result;
        }
    }
    async triggerDailyReset(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerDailyReset();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerDailyReset();
            return result;
        }
    }
    async updateTodayProblems(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTodayProblems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTodayProblems(arg0);
            return result;
        }
    }
    async updateYesterdayData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateYesterdayData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateYesterdayData();
            return result;
        }
    }
    async verifyAccountExists(): Promise<{
        accountCreated: boolean;
        exists: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAccountExists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAccountExists();
            return result;
        }
    }
}
function from_candid_Badge_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        todayProblems: bigint;
        profile: _UserProfile;
        recordCount: bigint;
    }]): {
    todayProblems: bigint;
    profile: UserProfile;
    recordCount: bigint;
} | null {
    return value.length === 0 ? null : from_candid_record_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Badge]): Badge | null {
    return value.length === 0 ? null : from_candid_Badge_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFine: bigint;
    totalProblemsSolved: bigint;
    todayProblems: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
}): {
    totalFine: bigint;
    totalProblemsSolved: bigint;
    todayProblems: bigint;
    badge?: Badge;
    currentStreak: bigint;
} {
    return {
        totalFine: value.totalFine,
        totalProblemsSolved: value.totalProblemsSolved,
        todayProblems: value.todayProblems,
        badge: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.badge)),
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todayProblems: bigint;
    profile: _UserProfile;
    recordCount: bigint;
}): {
    todayProblems: bigint;
    profile: UserProfile;
    recordCount: bigint;
} {
    return {
        todayProblems: value.todayProblems,
        profile: from_candid_UserProfile_n10(_uploadFile, _downloadFile, value.profile),
        recordCount: value.recordCount
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
}): {
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
} {
    return {
        name: value.name,
        totalFine: value.totalFine,
        totalProblemsSolved: value.totalProblemsSolved,
        badge: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.badge)),
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    totalFine: bigint;
    dailyRecords: Array<_DailyRecord>;
    totalProblemsSolved: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
}): {
    name: string;
    totalFine: bigint;
    dailyRecords: Array<DailyRecord>;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
} {
    return {
        name: value.name,
        totalFine: value.totalFine,
        dailyRecords: value.dailyRecords,
        totalProblemsSolved: value.totalProblemsSolved,
        badge: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.badge)),
        currentStreak: value.currentStreak
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dsaMasterCat: null;
} | {
    legendaryScholar: null;
} | {
    persistentRabbit: null;
}): Badge {
    return "dsaMasterCat" in value ? Badge.dsaMasterCat : "legendaryScholar" in value ? Badge.legendaryScholar : "persistentRabbit" in value ? Badge.persistentRabbit : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
}>): Array<{
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
}> {
    return value.map((x)=>from_candid_record_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    name: string;
    totalFine: bigint;
    dailyRecords: Array<_DailyRecord>;
    totalProblemsSolved: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
}>): Array<{
    name: string;
    totalFine: bigint;
    dailyRecords: Array<DailyRecord>;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
}> {
    return value.map((x)=>from_candid_record_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Badge_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): _Badge {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge?: Badge;
    currentStreak: bigint;
}): {
    name: string;
    totalFine: bigint;
    totalProblemsSolved: bigint;
    badge: [] | [_Badge];
    currentStreak: bigint;
} {
    return {
        name: value.name,
        totalFine: value.totalFine,
        totalProblemsSolved: value.totalProblemsSolved,
        badge: value.badge ? candid_some(to_candid_Badge_n19(_uploadFile, _downloadFile, value.badge)) : candid_none(),
        currentStreak: value.currentStreak
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): {
    dsaMasterCat: null;
} | {
    legendaryScholar: null;
} | {
    persistentRabbit: null;
} {
    return value == Badge.dsaMasterCat ? {
        dsaMasterCat: null
    } : value == Badge.legendaryScholar ? {
        legendaryScholar: null
    } : value == Badge.persistentRabbit ? {
        persistentRabbit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
